# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a9f793dbc5d009cf264984db21977b54d4fb426148fdfe688c725beb5511cb9fab34f0cedf2ec8e71fcb1ee0d2cdbcc267c465f2a8ca3861658f3eb2f4209fc

test:
  secret_key_base: ad4d8c469bf3a0ba77dfbf12ae4e79f7eb8cf02e48caab020276c38cdc77df03505e144790a94cc566cf32a30c276afd13afef772a8156aaab7fbb08e7a55617

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
